using CRIF_API.Client.Models.Common;

namespace CRIF_API.Client.Models.Responses;

/// <summary>
/// New Application Enquiry (NAE) Response
/// </summary>
public class NAEResponse : BaseResponse
{
    /// <summary>
    /// Enquired data (echo of request)
    /// </summary>
    public EnquiredData? EnquiredData { get; set; }

    /// <summary>
    /// Application codes (includes CB-generated codes)
    /// </summary>
    public ApplicationCodes? ApplicationCodes { get; set; }

    /// <summary>
    /// Credit report
    /// </summary>
    public CreditReport? CreditReport { get; set; }

    /// <summary>
    /// Credit score (if requested)
    /// </summary>
    public CreditScore? Score { get; set; }
}

/// <summary>
/// Enquired data - echo of request information
/// </summary>
public class EnquiredData
{
    public Individual? Individual { get; set; }
    public Company? Company { get; set; }
}

/// <summary>
/// Application codes in response
/// </summary>
public class ApplicationCodes
{
    /// <summary>
    /// CB Contract Code - generated by Credit Bureau
    /// </summary>
    public string? CBContractCode { get; set; }

    /// <summary>
    /// CB Subject Code - generated by Credit Bureau
    /// </summary>
    public string? CBSubjectCode { get; set; }

    /// <summary>
    /// Provider contract number (from request)
    /// </summary>
    public string? ProviderContractNo { get; set; }

    /// <summary>
    /// Provider application number (from request)
    /// </summary>
    public string? ProviderApplicationNo { get; set; }
}

/// <summary>
/// Credit score
/// </summary>
public class CreditScore
{
    /// <summary>
    /// Score value
    /// </summary>
    public decimal? ScoreValue { get; set; }

    /// <summary>
    /// Score description
    /// </summary>
    public string? ScoreDescription { get; set; }
}
